### ISSUE TITLE
Make TODOs optional on project update

### ISSUE THREAD

**Issue by cwasicki** [frequenz-floss/frequenz-repo-config-python#165] opened 2023-10-30 20:28 UTC
### What's needed?

Updating an existing project using the cookiecutter replay file *will create a new commit with all the changes to the overwritten files* and *[...] all the TODOs will come back, so there will be quite a bit of cleanup to do.* (see https://frequenz-floss.github.io/frequenz-repo-config-python/v0.7/#migrate-an-existing-project).

### Proposed solution

Option to suppress TODO comments.

### Use cases

Speed up version update since not all TODO comments have to be removed/ignored in the patch.

**Comment by llucax** [comment] 2023-10-31 08:37
Yeah, this should be part of a bigger revamp of updates. Basically update is not really supported, is just generating a new project. I think it will be hard to implement, and even when annoying, as the project matures updates should be less frequent, so the pay off will also diminish with time, so it will probably not happen soon.

Also the idea is to split the repo and have a pure library repo and a pure template repo, this also should make updating easier, as if the library changes it will be clear that templates don't need to be updated.

All that said avoid rendering the `TODO` comments should be pretty easy to implement **if** we have a way to tell when we are being regenerated (when a replay file was used, probably) and when we are being created from scratch.

**Comment by llucax** [comment] 2023-12-04 12:20
Duplicate of #186

**Closed as not planned by llucax** 2023-12-04 12:20 UTC
Labels: resolution:duplicate, type:enhancement, part:cookiecutter
